#!/bin/bash

# Corresponds to the EnvironmentFile in systemd service
# Override the default path by providing it as an arg
# e.g. add-env-vars "/some/path"
basePath=${1:-"$HOME"}
dotEnvFile="$basePath/.env.production"

if ! rm -rf "$dotEnvFile"; then
  echo "👹 Oops! Failed to remove env vars file"
  exit 1
fi

if ! touch "$dotEnvFile"; then
  echo "👹 Oops! Failed to create env vars file"
  exit 1
fi

# Include all service logic environment variables
declare -a envVars=(
  "PRIVATE_ZENDESK_EMAIL"
  "PRIVATE_ZENDESK_API_KEY"
  "PRIVATE_ZENDESK_HOSTNAME"
  "PUBLIC_SUPPORT_API_HOST"
  "SUPPORT_ALLOW_ORIGIN_ADDR"
  "SUPPORT_RATE_LIMIT_WINDOW_MINUTES"
  "SUPPORT_RATE_LIMIT_MAX_REQ"
  "SUPPORT_RATE_LIMIT_PATHS"
  "NODE_ENV"
)

addEnvironmentVar() {
  local varName="$1"
  if [[ -v varName && -z "${!varName}" ]]; then
    echo "👹 Oops! The ${varName} doesn't exist or is empty!"
    exit 1
  else
    echo "${varName}=\"${!varName}\"" >> "$dotEnvFile"
    echo "✅ Added ${varName} to $dotEnvFile"
  fi
}

for varName in "${envVars[@]}"; do
  addEnvironmentVar "$varName"
done

echo "👍Done! Adding environment variables."
