import { create } from 'domain';
import { title } from 'process';

export const PERMISSIONS_SECTIONS = {
  project: {
    title: 'Project',
    features: {
      editName: 'Edit Name',
      editAvatar: 'Edit Avatar',
      deleteProject: 'Delete Project',
    },
  },
  storage: {
    title: 'Storage',
    features: {
      editSettings: 'Edit Settings',
      uploadContent: 'Upload Files/Folders',
      editContentName: 'Edit Files/Folders Name',
      deleteContent: 'Delete Files/Folders',
      getInformation: 'Get Information',
      viewContentList: 'View Content List',
    },
  },
  site: {
    title: 'Sites',
    features: {
      createSite: 'Create Site',
      deploySite: 'Deploy Site',
      viewSiteOverview: 'View Site Overview',
      viewBuildSettings: 'View Build Settings',
      editBuildSettings: 'Edit Build Settings',
      viewEnvVariables: 'View Environment Variables',
      editEnvVariables: 'Edit Environment Variables',
      viewDeployments: 'View Deployments List',
      viewAnalytics: 'View Analytics',
      editSiteName: 'Edit Site Name',
      editSiteSlug: 'Edit Site Slug',
      editSiteAvatar: 'Edit Site Avatar',
      purgeCache: 'Purge Cache',
      deleteSite: 'Delete Site',
      andAndVerifyDomain: 'Add and Verify Domain',
      changePrimaryDomain: 'Change Primary Domain',
      deleteDomain: 'Delete Domain',
      addAndVerifyEns: 'Add and Verify ENS',
      deleteEns: 'Delete ENS',
      addGitIntegration: 'Add Git Integration',
      removeGitIntegration: 'Remove Git Integration',
    },
  },
  fleekFunctions: {
    title: 'Fleek Functions',
    features: {
      createFunction: 'Create Function',
      editSettings: 'Edit Settings',
      viewOverview: 'View Function Overview',
      deployFunction: 'Deploy Function',
      deleteFunction: 'Delete Function',
    },
  },
  ipns: {
    title: 'IPNS',
    features: {
      create: 'Create a Record',
      publish: 'Publish a Record',
      delete: 'Delete a Record',
      view: 'View Records',
    },
  },
  billing: {
    title: 'Billing',
    features: {
      viewBilling: 'View Billing',
      editBilling: 'Manage Billing',
    },
  },
  applicationCredentials: {
    title: 'Application Credentials',
    features: {
      view: 'View',
      create: 'Create',
      edit: 'Edit',
    },
  },
  team: {
    title: 'Team',
    features: {
      invite: 'Invite Team Members',
      changePermissions: 'Change Member Permissions',
      assignOwner: 'Assign Owner',
      deleteMember: 'Delete Member',
    },
  },
};

export const PERMISSIONS_ROLES = {
  owner: {
    features: {
      project: {
        editName: true,
        editAvatar: true,
        deleteProject: true,
      },
      storage: {
        editSettings: true,
        uploadContent: true,
        editContentName: true,
        deleteContent: true,
        getInformation: true,
        viewContentList: true,
      },
      site: {
        createSite: true,
        deploySite: true,
        viewSiteOverview: true,
        viewBuildSettings: true,
        editBuildSettings: true,
        viewEnvVariables: true,
        editEnvVariables: true,
        viewDeployments: true,
        viewAnalytics: true,
        editSiteName: true,
        editSiteSlug: true,
        editSiteAvatar: true,
        purgeCache: true,
        deleteSite: true,
        andAndVerifyDomain: true,
        changePrimaryDomain: true,
        deleteDomain: true,
        addAndVerifyEns: true,
        deleteEns: true,
        addGitIntegration: true,
        removeGitIntegration: true,
      },
      fleekFunctions: {
        createFunction: true,
        editSettings: true,
        viewOverview: true,
        deployFunction: true,
        deleteFunction: true,
      },
      ipns: {
        create: true,
        publish: true,
        delete: true,
        view: true,
      },
      billing: {
        viewBilling: true,
        editBilling: true,
      },
      applicationCredentials: {
        view: true,
        create: true,
        edit: true,
      },
      team: {
        invite: true,
        changePermissions: true,
        assignOwner: true,
        deleteMember: true,
      },
    },
    header: 'Owner',
  },
  admin: {
    features: {
      project: {
        editName: true,
        editAvatar: true,
        deleteProject: false,
      },
      storage: {
        editSettings: true,
        uploadContent: true,
        editContentName: true,
        deleteContent: true,
        getInformation: true,
        viewContentList: true,
      },
      site: {
        createSite: true,
        deploySite: true,
        viewSiteOverview: true,
        viewBuildSettings: true,
        editBuildSettings: true,
        viewEnvVariables: true,
        editEnvVariables: true,
        viewDeployments: true,
        viewAnalytics: true,
        editSiteName: true,
        editSiteSlug: true,
        editSiteAvatar: true,
        purgeCache: true,
        deleteSite: true,
        andAndVerifyDomain: true,
        changePrimaryDomain: true,
        deleteDomain: true,
        addAndVerifyEns: true,
        deleteEns: true,
        addGitIntegration: true,
        removeGitIntegration: true,
      },
      fleekFunctions: {
        createFunction: true,
        editSettings: true,
        viewOverview: true,
        deployFunction: true,
        deleteFunction: true,
      },
      ipns: {
        create: true,
        publish: true,
        delete: true,
        view: true,
      },
      billing: {
        viewBilling: true,
        editBilling: false,
      },
      applicationCredentials: {
        view: true,
        create: true,
        edit: true,
      },
      team: {
        invite: true,
        changePermissions: true,
        assignOwner: false,
        deleteMember: true,
      },
    },
    header: 'Admin',
  },
  member: {
    features: {
      project: {
        editName: true,
        editAvatar: true,
        deleteProject: false,
      },
      storage: {
        editSettings: false,
        uploadContent: true,
        editContentName: true,
        deleteContent: true,
        getInformation: true,
        viewContentList: true,
      },
      site: {
        createSite: true,
        deploySite: true,
        viewSiteOverview: true,
        viewBuildSettings: true,
        editBuildSettings: true,
        viewEnvVariables: true,
        editEnvVariables: true,
        viewDeployments: true,
        viewAnalytics: true,
        editSiteName: true,
        editSiteSlug: true,
        editSiteAvatar: true,
        purgeCache: true,
        deleteSite: false,
        andAndVerifyDomain: true,
        changePrimaryDomain: true,
        deleteDomain: true,
        addAndVerifyEns: true,
        deleteEns: true,
        addGitIntegration: true,
        removeGitIntegration: false,
      },
      fleekFunctions: {
        createFunction: true,
        editSettings: true,
        viewOverview: true,
        deployFunction: true,
        deleteFunction: true,
      },
      ipns: {
        create: true,
        publish: true,
        delete: true,
        view: true,
      },
      billing: {
        viewBilling: false,
        editBilling: false,
      },
      applicationCredentials: {
        view: true,
        create: true,
        edit: true,
      },
      team: {
        invite: false,
        changePermissions: false,
        assignOwner: false,
        deleteMember: false,
      },
    },
    header: 'Member',
  },
  readOnly: {
    features: {
      project: {
        editName: false,
        editAvatar: false,
        deleteProject: false,
      },
      storage: {
        editSettings: false,
        uploadContent: false,
        editContentName: false,
        deleteContent: false,
        getInformation: true,
        viewContentList: true,
      },
      site: {
        createSite: false,
        deploySite: false,
        viewSiteOverview: true,
        viewBuildSettings: true,
        editBuildSettings: false,
        viewEnvVariables: true,
        editEnvVariables: false,
        viewDeployments: true,
        viewAnalytics: true,
        editSiteName: false,
        editSiteSlug: false,
        editSiteAvatar: false,
        purgeCache: false,
        deleteSite: false,
        andAndVerifyDomain: false,
        changePrimaryDomain: false,
        deleteDomain: false,
        addAndVerifyEns: false,
        deleteEns: false,
        addGitIntegration: false,
        removeGitIntegration: false,
      },
      fleekFunctions: {
        createFunction: false,
        editSettings: false,
        viewOverview: true,
        deployFunction: false,
        deleteFunction: false,
      },
      ipns: {
        create: false,
        publish: false,
        delete: false,
        view: true,
      },
      billing: {
        viewBilling: false,
        editBilling: false,
      },
      applicationCredentials: {
        view: true,
        create: false,
        edit: false,
      },
      team: {
        invite: false,
        changePermissions: false,
        assignOwner: false,
        deleteMember: false,
      },
    },
    header: 'Read Only',
  },
};
