name: 🔧 Build (dry-run)

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  build-dry-run:
    runs-on: ubuntu-latest
    env:
      PRIVATE_MEILISEARCH_DOCUMENTS_ADMIN_API_KEY: dry.run
      PUBLIC_MEILISEARCH_DOCUMENTS_CLIENT_API_KEY: dry.run
      PUBLIC_MEILISEARCH_HOST: dry.run
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install
        run: npm ci

      - name: Build site
        run: npm run build
