name: 🎀 Code Format (Verification)

on:
 push:
    branches:
      - main
      - develop
 pull_request:

jobs:
 prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Code format check
        id: fmt_check
        run: npm run fmt:check || echo "::set-output name=exit_code::$?"

      - name: Auto-format (Markdown files)
        if: steps.fmt_check.outputs.exit_code != '0' && github.event_name == 'pull_request' && github.ref == 'refs/heads/develop'
        run: npx prettier --write "src/**/*.{md,mdx}"

      - name: Commit formatted (Markdown files)
        if: steps.fmt_check.outputs.exit_code != '0' && github.ref == 'refs/heads/develop'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "chore: 🤖 code format" || echo "🦖 Skipped! No changes found and will not commit..."
          git push
