name: 🫡 Commit checkups (Verification)

on:
 push:
    branches:
      - main
      - develop
 pull_request:

jobs:
 commit_checkups:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Commit checks
        run: ./.husky/pre-commit
