name: 🚜 Search (Indexer)
on:
  push:
    branches: [ main ]

jobs:
  meilisearch:
    name: MeiliSearch Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Blog Indexation
        run: |
          npm run search:index_blog_prod
        env:
          PUBLIC_MEILISEARCH_INDEX_BLOG: ${{ secrets.PUBLIC_MEILISEARCH_INDEX_BLOG }}
          PUBLIC_MEILISEARCH_HOST: ${{ secrets.PUBLIC_MEILISEARCH_HOST }}
          PUBLIC_MEILISEARCH_DOCUMENTS_CLIENT_API_KEY: ${{ secrets.PUBLIC_MEILISEARCH_DOCUMENTS_CLIENT_API_KEY }}
